#import '../fragments/client'
#import '../fragments/client/client-detail'

query clientsQuery (
  $search: String
) {
  clients (
    search: $search
  ) {
    ...client
    ...clientClientDetail
  }
}